# Fluent bit
# https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml
# https://docs.fluentbit.io/manual/pipeline/outputs/loki
# Internal endpoints
# http://loki-gateway.monitoring.svc.cluster.local/   
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: fluent-bit
  namespace: kube-system
spec:
  repo: https://fluent.github.io/helm-charts
  chart: fluent-bit
  targetNamespace: monitoring
  createNamespace: true  
  valuesContent: |-
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 15s
      scrapeTimeout: 15s
      jobLabel: fluentbit
      selector:
        release: prom  
    dashboards:
      enabled: false

    config:
      service: |
        [SERVICE]
            Flush               2
            Log_Level           info
            Daemon              off
            Parsers_File        parsers
            Parsers_File        custom_parsers.conf
            HTTP_Server         On
            HTTP_Listen         0.0.0.0
            HTTP_Port           2020
            Health_Check On 
            HC_Errors_Count 5
            HC_Retry_Failure_Count 5
            HC_Period 10
            storage.path        /var/data/storage
            storage.max_chunks_up 256
            storage.sync        full
            storage.backlog.mem_limit 5M
            storage.metrics     on
    
      inputs: |
        [INPUT]
            name                http
            listen              0.0.0.0
            port                9045
            storage.type        filesystem
            buffer_max_size     4M
            buffer_chunk_size   512K
    
        [INPUT]
            name                http
            listen              0.0.0.0
            port                9046
            storage.type        filesystem
            storage.pause_on_chunks_overlimit Off
            tls                 Off
            tls.verify          Off
            storage.type        filesystem
            buffer_max_size     8M
            buffer_chunk_size   512K
    
        [INPUT]
            Name                tail
            Path                /var/log/containers/*.log
            Exclude_Path        /var/log/containers/*_kube-fluentbit_*.log
            multiline.parser    docker, cri
            Tag                 kube.*
            Skip_Long_Lines     On
            Refresh_Interval    10
            storage.type        filesystem
            DB                  fb_kube.db
            DB.locking          true
            Buffer_Chunk_Size   256KB
            Buffer_Max_Size     256KB
    
        [INPUT]
            Name                tail
            Path                /var/log/containers/*_kube-fluentbit_*.log
            multiline.parser    docker, cri
            Tag                 fluent.*
            Skip_Long_Lines     On
            Refresh_Interval    10
            storage.type        filesystem
            DB                  fb_fluent.db
            DB.locking          true
            Buffer_Chunk_Size   256KB
            Buffer_Max_Size     256KB
    
        [INPUT]
            Name                tail
            Path                /var/log/messages
            Path_Key            log_file
            Parser              syslog
            Tag                 host.messages
            Skip_Long_Lines     On
            Refresh_Interval    10
            storage.type        filesystem
            DB                  fb_host.db
            DB.locking          true
            Buffer_Chunk_Size   256KB
            Buffer_Max_Size     256KB
    
        [INPUT]
            Name                fluentbit_metrics
            Tag                 internal_metrics
            Scrape_Interval     2
    
      filters: |
        [FILTER] 
            Name                kubernetes
            Buffer_Size         1024k
            Match               kube.*
            Merge_Log           On
            Keep_Log            Off
            K8S-Logging.Parser  On
            K8S-Logging.Exclude On
        [FILTER]
            Name                kubernetes
            Buffer_Size         1024k
            Match               kube-otel.*
            Merge_Log           On
            Keep_Log            Off
            K8S-Logging.Parser  On
            K8S-Logging.Exclude On
            Kube_Tag_Prefix     kube-otel.var.log.containers.
        [FILTER]
            Name modify
            Match kube.*
            Add ring lab
        [FILTER]
            Name                  rewrite_tag
            Match                 kube.*
            Emitter_Mem_Buf_Limit 400M
            Rule                  $kubernetes_container_name ^(containerized-tests)$ sdlc false
            Emitter_Storage.type  filesystem
        [FILTER]
            Name                  rewrite_tag
            Match                 kube.*
            Emitter_Mem_Buf_Limit 128M
            Rule                  $ring dropdata dropdata false
            Emitter_Storage.type  memory
        [FILTER]
            Name                modify
            Match               *
            Rename              msg log
            Condition           A_key_matches msg 
        [FILTER]
            Name                modify
            Match               *
            Rename              message log
            Condition           A_key_matches message  
        [FILTER]
            Name                modify
            Match               *
            Remove              stream
            Remove              time
            Condition           Key_exists resourceLogs
        [FILTER]
            Name                  rewrite_tag
            Match                 kube.*
            Emitter_Mem_Buf_Limit 400M
            Rule                  $resourceLogs[0]['instrumentationLibraryLogs'][0]['instrumentationLibrary']['name'] ^(OpenTelemetry)$ kube-otel-old.$TAG[1].$TAG[2].$TAG[3].$TAG[4].$TAG[5] false
            Emitter_Storage.type  filesystem
        [FILTER]
            Name                  rewrite_tag
            Match                 kube.*
            Emitter_Mem_Buf_Limit 50M
            Rule                  $resourceLogs[0]['scopeLogs'][0]['scope']['name'] ^(OpenTelemetry)$ kube-otel-new.$TAG[1].$TAG[2].$TAG[3].$TAG[4].$TAG[5] false
            Emitter_Storage.type  filesystem
        [FILTER]
            Name                  rewrite_tag
            Match                 kube-otel-old.*
            Emitter_Mem_Buf_Limit 50M
            Rule                  $resourceLogs[0]['instrumentationLibraryLogs'][0]['instrumentationLibrary']['name'] ^(OpenTelemetry)$ kube-otel-old-datap.$TAG[1].$TAG[2].$TAG[3].$TAG[4].$TAG[5] true
            Emitter_Storage.type  filesystem
        [FILTER]
            Name                  rewrite_tag
            Match                 kube.*
            Emitter_Mem_Buf_Limit 400M
            Rule                  $dataPlatformEventType ^(.+)$ kafka false
        [FILTER]
            Name record_modifier
            Match kafka
            Record ring lab
            Remove_key kubernetes
            Remove_key stream
            Remove_key time
        [FILTER]
            Name                  grep
            Match                 kube-otel-old.*
            Exclude               $resourceLogs[0]['instrumentationLibraryLogs'][0]['logs'][0]['body']['stringValue'] ^Request finished HTTP\/1.1 GET http:.+8080\/api\/v1\/health - - - 200 - text\/plain .+$
            Exclude               $resourceLogs[0]['instrumentationLibraryLogs'][0]['logs'][0]['body']['stringValue'] ^Request starting HTTP\/1.1 GET http:.+8080\/api\/v1\/health - -$
            Exclude               $resourceLogs[0]['instrumentationLibraryLogs'][0]['logs'][0]['body']['stringValue'] ^Executed endpoint \\u0027Health checks\\u0027$
        [FILTER]
            Name                  grep
            Match                 kube.*
            Exclude               $log /envoy-hc
        [FILTER]
            Name                  grep
            Match                 kube.*
            Exclude               $log Deprecated field: type envoy
        [FILTER]
            Name                  grep
            Match                 kube.*
            Exclude               $log ^.*The error is not retryable. Dropping data.*TRACE_TOO_LARGE.*
        [FILTER]
            Name                  grep
            Match                 kube.*
            Exclude               $log ignoring key that's not used for signing
        [FILTER]
            Name                  grep
            Match                 kube.*
            Exclude               log ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>F) $
        [FILTER]
            Name                  grep
            Match                 kube.*
            Logical_Op            and
            Exclude               $log /.*INFO.*/
            Exclude               $kubernetes['namespace_name'] calico-system
        [FILTER]
            Name                modify
            Match               kube.*
            Condition           Key_Does_Not_Exist severity
            Set                 severity Unknown
        [FILTER]
            Name                modify
            Match               kube.*
            Condition           Key_value_does_not_match severity (Debug|Information|Warning|Error|Critical)
            Set                 severity_state Non-Standard
        # [FILTER]
        #     Name lua
        #     Match kube-otel-old.*
        #     Log_Level info
        #     Script change_label.lua
        #     call rename_label
    
      outputs: |

        [OUTPUT]
            Name                forward
            Host                ${HOST_IP}
            Port                8007
            Match               kube-otel-new.*
            storage.total_limit_size 1G
    
        [OUTPUT]
            Name          loki
            Match         fluent.*
            Log_Level     info
            Host          loki-gateway.monitoring.svc.cluster.local
            port          3100
            labels        job=fluentbit, ring=lab, stamp=local
            label_map_path /fluent-bit/etc/conf/labelmap.conf
            storage.total_limit_size 1G
    
        [OUTPUT]
            Name          loki
            Match         auditevents
            Log_Level     info
            Host          loki-gateway.monitoring.svc.cluster.local
            port          3100
            labels        job=auditevents, ring=lab, stamp=local
            label_map_path /fluent-bit/etc/conf/labelmap.conf
            storage.total_limit_size 1G
    
        [OUTPUT]
            Name          loki
            Match         kube.*
            Log_Level     info
            Host          loki-gateway.monitoring.svc.cluster.local
            port          3100
            labels        job=auditevents, ring=lab, stamp=local
            label_map_path /fluent-bit/etc/conf/labelmap.conf
            storage.total_limit_size 1G
    
        [OUTPUT]
            Name          loki
            Match         host.*
            Log_Level     info
            Host          loki-gateway.monitoring.svc.cluster.local
            port          3100
            labels        job=auditevents, ring=lab, stamp=local
            label_map_path /fluent-bit/etc/conf/labelmap.conf
            storage.total_limit_size 1G
    
        [OUTPUT]
            Name          loki
            Match         sdlc.*
            Log_Level     info
            Host          loki-gateway.monitoring.svc.cluster.local
            port          3100
            labels        job=auditevents, ring=lab, stamp=local
            label_map_path /fluent-bit/etc/conf/labelmap.conf
            storage.total_limit_size 1G
        
        [OUTPUT]
            Name                null
            Match               dropdata
            storage.total_limit_size 1G
    
        [OUTPUT]
            Name                prometheus_exporter
            Host                0.0.0.0
            Port                2021
            Match               internal_metrics


      customParsers: |
        [PARSER]
            Name                docker_no_time
            Format              json
            Time_Keep           Off
            Time_Key            time
            Time_Format         %Y-%m-%dT%H:%M:%S.%L
        [PARSER]
            Name                syslog
            Format              regex
            Regex               ^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<log>.*)$
            Time_Key            time
            Time_Format         %b %d %H:%M:%S

      extraFiles:
        labelmap.conf: |
          {
            "kubernetes": {
              "namespace_name": "k8s_namespace_name"
            },
            "service_name": "service_name"
          }