# Kube state metrics
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-state-metrics
  targetNamespace: monitoring
  createNamespace: true  

# pushgateway
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-pushgateway
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: prometheus-pushgateway
  targetNamespace: monitoring
  createNamespace: true  

# Prometheus
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetNamespace: monitoring
  createNamespace: true  
  valuesContent: |-
    grafana:
      enabled: false
    nodeExporter:
      enabled: false
    prometheus:
      service:
        type: LoadBalancer
